---
- name: Get Content from using ID
  uri:
    url: '{{ confluence_space_source_url }}/wiki/rest/api/content/42139778?expand=body.storage,space,ancestors'
    method: GET
    user: '{{ source_confluence_site_username }}'
    password: '{{ source_confluence_site_password }}'
    force_basic_auth: yes
    status_code: 200
    return_content: yes
  register: content_json
  no_log: false
