version: '2'
services:
  drupal:
    image: drupal:latest
    ports:
    - '8080:80'
    depends_on:
    - postgres      
    
  postgres:
    image: postgres:latest
    environment:
    - POSTGRES_PASSWORD=postgres
    ports:
    - '5432:5432'      

  
