---

# Configure DNS Server(s)
- hosts: dns
  pre_tasks:
  - name: "Include the views"
    include_vars: vars/views.yml
    delegate_to: localhost
  roles:
    - role: ../../galaxy/infra-ansible/roles/dns-server
