---
- name: "Set up the nagios targets"
  hosts: nagios-targets
  roles:
  - role: ../../galaxy/infra-ansible/roles/nagios-target
    
- name: "Set up nagios server"
  hosts: nagios-servers
  roles:
  - role: ../../galaxy/infra-ansible/roles/nagios-server

