---
git_repo_home: "/opt/git"
ose_git_repo_home: "{{ git_repo_home }}/openshift"
git_user: "git"

# List of Authorized Keys to Add
git_user_authorized_keys:

ose_example_repos:
 - "https://github.com/openshift/cakephp-ex.git"
 - "https://github.com/openshift/dancer-ex.git"
 - "https://github.com/jboss-openshift/openshift-quickstarts.git"
 - "https://github.com/openshift/django-ex.git"
 - "https://github.com/openshift/nodejs-ex.git"
 - "https://github.com/openshift/rails-ex.git"
